insert into city (name) values ('Yuanmen');
insert into city (name) values ('Duncan Town');
insert into city (name) values ('Pechersk');
insert into city (name) values ('Pojan');
insert into city (name) values ('San Vicente');
insert into city (name) values ('Nipawin');
insert into city (name) values ('Madagali');
insert into city (name) values ('Hushi');
insert into city (name) values ('Solna');
insert into city (name) values ('Užice');
insert into city (name) values ('Melikkrajan');
insert into city (name) values ('Luxi');
insert into city (name) values ('Savalou');
insert into city (name) values ('L''Assomption');
insert into city (name) values ('Tomakivka');
insert into city (name) values ('Biao');
insert into city (name) values ('Biguaçu');
insert into city (name) values ('Jinping');
insert into city (name) values ('Kirkuk');
insert into city (name) values ('Skuhrov nad Bělou');
insert into city (name) values ('Tupanciretã');
insert into city (name) values ('Askersund');
insert into city (name) values ('Caocun');
insert into city (name) values ('Taibao');
insert into city (name) values ('Serra D''El Rei');
insert into city (name) values ('Pingle');
insert into city (name) values ('Nagoya-shi');
insert into city (name) values ('Jāsk');
insert into city (name) values ('Bonak');
insert into city (name) values ('Yunxian Chengguanzhen');
insert into city (name) values ('Vitrolles');
insert into city (name) values ('Petrikov');
insert into city (name) values ('Valle de Ángeles');
insert into city (name) values ('Sakule');
insert into city (name) values ('Krasnofarfornyy');
insert into city (name) values ('Sinamaica');
insert into city (name) values ('Danderyd');
insert into city (name) values ('Belén de los Andaquíes');
insert into city (name) values ('Pakel');
insert into city (name) values ('Aragua de Barcelona');
insert into city (name) values ('San Nicolás');
insert into city (name) values ('Alexandria');
insert into city (name) values ('Vila Boa do Bispo');
insert into city (name) values ('Bantilan');
insert into city (name) values ('Putang');
insert into city (name) values ('Nikhom Phattana');
insert into city (name) values ('Milwaukee');
insert into city (name) values ('Bantal');
insert into city (name) values ('Castlebridge');
insert into city (name) values ('Le Blanc-Mesnil');
insert into city (name) values ('Waepana');
insert into city (name) values ('Bibiani');
insert into city (name) values ('Zrenjanin');
insert into city (name) values ('Modot');
insert into city (name) values ('Mashava');
insert into city (name) values ('Goodlands');
insert into city (name) values ('Hashimoto');
insert into city (name) values ('Gaptsakh');
insert into city (name) values ('Uppsala');
insert into city (name) values ('Mae Lan');
insert into city (name) values ('Shitong');
insert into city (name) values ('Madaoua');
insert into city (name) values ('Złota');
insert into city (name) values ('Santander');
insert into city (name) values ('Duisburg');
insert into city (name) values ('Yinying');
insert into city (name) values ('Yisuhe');
insert into city (name) values ('Morazán');
insert into city (name) values ('Eaubonne');
insert into city (name) values ('Kivsharivka');
insert into city (name) values ('Karpinsk');
insert into city (name) values ('La Escondida');
insert into city (name) values ('Sabae');
insert into city (name) values ('Bouna');
insert into city (name) values ('Dřevohostice');
insert into city (name) values ('Alverca do Ribatejo');
insert into city (name) values ('San Rafael');
insert into city (name) values ('Patong');
insert into city (name) values ('Impendle');
insert into city (name) values ('Nakhon Sawan');
insert into city (name) values ('Sundumbili');
insert into city (name) values ('Panalingaan');
insert into city (name) values ('Tingqian');
insert into city (name) values ('Masina');
insert into city (name) values ('Bijela');
insert into city (name) values ('Beizhouzi');
insert into city (name) values ('Kaliuling');
insert into city (name) values ('Francisco Beltrão');
insert into city (name) values ('Amieira');
insert into city (name) values ('Bahe');
insert into city (name) values ('Partizan');
insert into city (name) values ('Noyemberyan');
insert into city (name) values ('Mekarsari');
insert into city (name) values ('Czarna');
insert into city (name) values ('Varnsdorf');
insert into city (name) values ('Gort');
insert into city (name) values ('Arauco');
insert into city (name) values ('Pontevedra');
insert into city (name) values ('Tushi');
insert into city (name) values ('Krajan');
