INSERT INTO `country` (`id`, `name`) VALUES (null,  'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Albania');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Algeria');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'American Samoa');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Angola');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Antarctica');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Antigua and Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Argentina');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Australia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Austria');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Azerbaijan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Belarus');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Belgium');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Belize');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Benin');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bosnia and Herzegovina');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bouvet Island');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Brazil');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'British Indian Ocean Territory');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Brunei Darussalam');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Cambodia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Cameroon');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Canada');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Cape Verde');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Cayman Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Central African Republic');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Chad');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Chile');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'China');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Christmas Island');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Cocos (Keeling) Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Colombia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Comoros');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Democratic Republic of the Congo');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Republic of Congo');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Cook Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Croatia (Hrvatska)');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Cuba');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Cyprus');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Czech Republic');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Denmark');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Dominica');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Dominican Republic');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'East Timor');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Egypt');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Equatorial Guinea');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Estonia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Ethiopia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Falkland Islands (Malvinas)');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Faroe Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Finland');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'France');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'France, Metropolitan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'French Guiana');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'French Polynesia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'French Southern Territories');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Georgia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Germany');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Greece');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Greenland');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Guam');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Heard and Mc Donald Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Hong Kong');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Hungary');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Iceland');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'India');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Isle of Man');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Iran (Islamic Republic of)');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Iraq');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Ireland');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Israel');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Italy');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Ivory Coast');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Jamaica');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Japan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Jordan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Kazakhstan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Korea, Democratic People''s Republic of');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Korea, Republic of');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Kosovo');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Kyrgyzstan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Lao People''s Democratic Republic');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Latvia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Lebanon');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Libyan Arab Jamahiriya');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Lithuania');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Luxembourg');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Macau');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'North Macedonia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Madagascar');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Malaysia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Maldives');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Mali');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Malta');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Marshall Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Mexico');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Micronesia, Federated States of');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Moldova, Republic of');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Morocco');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Mozambique');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Myanmar');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Netherlands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Netherlands Antilles');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'New Caledonia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'New Zealand');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Niger');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Niue');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Norfolk Island');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Northern Mariana Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Norway');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Oman');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Palau');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Palestine');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Panama');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Papua New Guinea');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Peru');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Philippines');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Poland');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Portugal');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Reunion');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Romania');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Russian Federation');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Saint Kitts and Nevis');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Saint Vincent and the Grenadines');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Sao Tome and Principe');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Saudi Arabia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Seychelles');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Solomon Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'South Africa');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'South Georgia South Sandwich Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'South Sudan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Spain');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'St. Helena');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'St. Pierre and Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Svalbard and Jan Mayen Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Swaziland');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Sweden');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Switzerland');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Syrian Arab Republic');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Tajikistan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Tanzania, United Republic of');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Thailand');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Togo');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Trinidad and Tobago');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Turkey');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Turks and Caicos Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Ukraine');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'United Arab Emirates');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'United Kingdom');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'United States');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'United States minor outlying islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Uzbekistan');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Vatican City State');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Virgin Islands (British)');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Virgin Islands (U.S.)');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Wallis and Futuna Islands');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Western Sahara');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Yemen');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES (null,  'Zimbabwe');